// ✅ Sample product data for seeding the database
const sampleProducts = [
  {
    name: "Intel Core i9-13900K",
    category: "CPU",
    brand: "Intel",
    attributes: {
      Cores: "24 (8P + 16E)",
      Threads: "32",
      "Base Clock": "3.0 GHz",
      "Boost Clock": "5.8 GHz",
      TDP: "125W",
      Socket: "LGA1700",
    },
    originalPrice: 699,
    discountPercentage: 5,
    stock: 20,
    image: "https://example.com/intel-i9.jpg",
    description: "High-performance CPU for gaming and content creation.",
  },
  {
    name: "NVIDIA GeForce RTX 4090",
    category: "GPU",
    brand: "NVIDIA",
    attributes: {
      Memory: "24GB GDDR6X",
      "Clock Speed": "2235 MHz",
      "Power Consumption": "450W",
      Cooling: "Triple Fan",
    },
    originalPrice: 1999,
    discountPercentage: 10,
    stock: 10,
    image: "https://example.com/rtx4090.jpg",
    description: "The most powerful gaming GPU with ray tracing and AI features.",
  },
  {
    name: "ASUS ROG Strix Z790-E",
    category: "Motherboard",
    brand: "ASUS",
    attributes: {
      Chipset: "Z790",
      Socket: "LGA1700",
      "Form Factor": "ATX",
      "RAM Support": "DDR5 up to 7200 MHz",
      "PCIe Slots": "PCIe 5.0 x16",
      WiFi: "WiFi 6E",
    },
    originalPrice: 499,
    discountPercentage: 7,
    stock: 15,
    image: "https://example.com/asus-z790.jpg",
    description: "High-end gaming motherboard with next-gen connectivity.",
  },
  {
    name: "Corsair Vengeance RGB 32GB",
    category: "RAM",
    brand: "Corsair",
    attributes: {
      "Memory Type": "DDR5",
      Capacity: "32GB (2x16GB)",
      Speed: "6000 MHz",
      "CAS Latency": "CL36",
      RGB: "Yes",
    },
    originalPrice: 199,
    discountPercentage: 8,
    stock: 30,
    image: "https://example.com/corsair-ram.jpg",
    description: "High-speed DDR5 memory with customizable RGB lighting.",
  },
  {
    name: "Samsung 990 Pro 2TB NVMe SSD",
    category: "Storage",
    brand: "Samsung",
    attributes: {
      Capacity: "2TB",
      Interface: "PCIe 4.0",
      "Read Speed": "7450 MB/s",
      "Write Speed": "6900 MB/s",
    },
    originalPrice: 299,
    discountPercentage: 5,
    stock: 25,
    image: "https://example.com/samsung-990pro.jpg",
    description: "Ultra-fast SSD for gaming and professional workloads.",
  },
  {
    name: "ASUS ROG Zephyrus G16",
    category: "GamingLaptop",
    brand: "ASUS",
    attributes: {
      Processor: "Intel Core i9-13900HX",
      GPU: "NVIDIA RTX 4080",
      RAM: "32GB DDR5",
      Storage: "1TB NVMe SSD",
      Display: "16-inch QHD 240Hz",
    },
    originalPrice: 2899,
    discountPercentage: 12,
    stock: 10,
    image: "https://example.com/rog-g16.jpg",
    description: "Powerful gaming laptop with a 240Hz refresh rate.",
  },
  {
    name: "Elden Ring",
    category: "PCGames",
    brand: "FromSoftware",
    attributes: {
      Genre: "Action RPG",
      Platform: "PC",
      Multiplayer: "Yes",
      Developer: "FromSoftware",
    },
    originalPrice: 59,
    discountPercentage: 15,
    stock: 50,
    image: "https://example.com/eldenring.jpg",
    description: "Award-winning open-world action RPG.",
  },
  {
    name: "Secretlab Titan Evo 2023",
    category: "GamingChair",
    brand: "Secretlab",
    attributes: {
      Material: "Hybrid Leatherette",
      Adjustability: "4D Armrests, Recline, Lumbar Support",
      "Weight Capacity": "290 lbs",
    },
    originalPrice: 499,
    discountPercentage: 10,
    stock: 20,
    image: "https://example.com/secretlab-titan.jpg",
    description: "Ergonomic gaming chair with advanced adjustability.",
  },
  {
    name: "SteelSeries Arctis Pro Wireless",
    category: "Headset",
    brand: "SteelSeries",
    attributes: {
      Sound: "Hi-Res Audio",
      Microphone: "ClearCast Bidirectional",
      "Battery Life": "20 Hours",
      Connectivity: "Wireless 2.4GHz + Bluetooth",
    },
    originalPrice: 349,
    discountPercentage: 12,
    stock: 10,
    image: "https://example.com/arctispro.jpg",
    description:
      "Premium wireless gaming headset with Hi-Res Audio and dual connectivity.",
  },
  {
    name: "Elgato Stream Deck XL",
    category: "StreamingGear",
    brand: "Elgato",
    attributes: {
      Keys: "32 LCD Keys",
      Compatibility: "Windows, macOS",
      Customization: "Fully Customizable Actions",
    },
    originalPrice: 249,
    discountPercentage: 10,
    stock: 15,
    image: "https://example.com/streamdeck.jpg",
    description: "Advanced stream control with customizable LCD keys.",
  },
];

// ✅ Export data for use in seeding scripts
export default sampleProducts;
