// File: server/utils/sampleData.js

const sampleProducts = [
  {
    name: "Intel Core i9-13900K",
    category: "CPU",
    brand: "Intel",
    specifications: [
      { key: "Cores", value: "24 (8P + 16E)" },
      { key: "Threads", value: "32" },
      { key: "Base Clock", value: "3.0 GHz" },
      { key: "Boost Clock", value: "5.8 GHz" },
      { key: "Socket", value: "LGA1700" },
    ],
    originalPrice: 699,
    discountPercentage: 5,
    finalPrice: 664.05,
    stock: 20,
    availability: "In Stock",
    images: ["https://example.com/images/intel-i9-13900k.jpg"],
    description: "Top-tier gaming and content creation processor.",
    sku: "CPU-INT-13900K",
    features: ["Unlocked", "Integrated Graphics"],
    warranty: "3 years",
    weight: 0.3,
    dimensions: { length: 4, width: 4.5, height: 2 },
    ratings: { average: 4.8, totalReviews: 320 },
    isActive: true,
    isFeatured: true,
    salesCount: 1200,
  },
  {
    name: "AMD Ryzen 9 7900X",
    category: "CPU",
    brand: "AMD",
    specifications: [
      { key: "Cores", value: "12" },
      { key: "Threads", value: "24" },
      { key: "Base Clock", value: "4.7 GHz" },
      { key: "Boost Clock", value: "5.6 GHz" },
      { key: "Socket", value: "AM5" },
    ],
    originalPrice: 549,
    discountPercentage: 10,
    finalPrice: 494.1,
    stock: 18,
    availability: "In Stock",
    images: ["https://example.com/images/ryzen-7900x.jpg"],
    description: "Powerful multitasking processor for gamers and creators.",
    sku: "CPU-AMD-7900X",
    features: ["PCIe 5.0", "DDR5 Support"],
    warranty: "3 years",
    weight: 0.35,
    dimensions: { length: 4, width: 4.5, height: 2 },
    ratings: { average: 4.7, totalReviews: 290 },
    isActive: true,
    isFeatured: false,
    salesCount: 1100,
  },
  {
    name: "NVIDIA GeForce RTX 4090",
    category: "GPU",
    brand: "NVIDIA",
    specifications: [
      { key: "Memory", value: "24GB GDDR6X" },
      { key: "Clock Speed", value: "2235 MHz" },
      { key: "TDP", value: "450W" },
      { key: "Interface", value: "PCIe 4.0" },
    ],
    originalPrice: 1999,
    discountPercentage: 10,
    finalPrice: 1799.1,
    stock: 8,
    availability: "In Stock",
    images: ["https://example.com/images/rtx-4090.jpg"],
    description: "Flagship GPU for 4K gaming and AI workloads.",
    sku: "GPU-NVD-4090",
    features: ["Ray Tracing", "DLSS 3.0"],
    warranty: "2 years",
    weight: 1.6,
    dimensions: { length: 13, width: 5.5, height: 2.5 },
    ratings: { average: 4.9, totalReviews: 600 },
    isActive: true,
    isFeatured: true,
    salesCount: 900,
  },
  {
    name: "ASUS ROG Strix Z790-E",
    category: "Motherboard",
    brand: "ASUS",
    specifications: [
      { key: "Chipset", value: "Z790" },
      { key: "Socket", value: "LGA1700" },
      { key: "Form Factor", value: "ATX" },
      { key: "RAM Support", value: "DDR5" },
    ],
    originalPrice: 499,
    discountPercentage: 7,
    finalPrice: 464.07,
    stock: 15,
    availability: "In Stock",
    images: ["https://example.com/images/asus-z790e.jpg"],
    description: "Enthusiast-grade motherboard with premium features.",
    sku: "MB-ASUS-Z790E",
    features: ["PCIe 5.0", "Wi-Fi 6E"],
    warranty: "3 years",
    weight: 1.2,
    dimensions: { length: 12, width: 9.6, height: 2 },
    ratings: { average: 4.7, totalReviews: 270 },
    isActive: true,
    isFeatured: true,
    salesCount: 700,
  },
  {
    name: "Corsair Vengeance 32GB DDR5",
    category: "RAM",
    brand: "Corsair",
    specifications: [
      { key: "Capacity", value: "32GB (2x16GB)" },
      { key: "Speed", value: "6000MHz" },
      { key: "Type", value: "DDR5" },
    ],
    originalPrice: 189,
    discountPercentage: 10,
    finalPrice: 170.1,
    stock: 40,
    availability: "In Stock",
    images: ["https://example.com/images/corsair-ddr5.jpg"],
    description: "High-speed DDR5 RAM with RGB lighting.",
    sku: "RAM-COR-32GB-DDR5",
    features: ["RGB Lighting", "Low Latency"],
    warranty: "Lifetime",
    weight: 0.15,
    dimensions: { length: 5.25, width: 1.2, height: 0.25 },
    ratings: { average: 4.6, totalReviews: 200 },
    isActive: true,
    isFeatured: false,
    salesCount: 1400,
  },
  {
    name: "Samsung 980 PRO 1TB NVMe SSD",
    category: "Storage",
    brand: "Samsung",
    specifications: [
      { key: "Capacity", value: "1TB" },
      { key: "Interface", value: "PCIe 4.0" },
      { key: "Form Factor", value: "M.2 2280" },
    ],
    originalPrice: 159,
    discountPercentage: 12,
    finalPrice: 139.92,
    stock: 35,
    availability: "In Stock",
    images: ["https://example.com/images/samsung-980pro.jpg"],
    description: "High-speed NVMe SSD for gaming and productivity.",
    sku: "SSD-SAM-980PRO-1TB",
    features: ["Thermal Control", "Samsung Magician Support"],
    warranty: "5 years",
    weight: 0.07,
    dimensions: { length: 3.15, width: 0.87, height: 0.09 },
    ratings: { average: 4.8, totalReviews: 450 },
    isActive: true,
    isFeatured: false,
    salesCount: 2000,
  },
  {
    name: "Cooler Master Hyper 212 Black Edition",
    category: "Cooler",
    brand: "Cooler Master",
    specifications: [
      { key: "Type", value: "Air Cooler" },
      { key: "Fan Speed", value: "650–2000 RPM" },
      { key: "Compatibility", value: "Intel & AMD Sockets" },
    ],
    originalPrice: 49,
    discountPercentage: 10,
    finalPrice: 44.1,
    stock: 60,
    availability: "In Stock",
    images: ["https://example.com/images/hyper-212.jpg"],
    description: "Popular air cooler with great performance and low noise.",
    sku: "CLR-CM-H212",
    features: ["Quiet Operation", "Easy Mounting"],
    warranty: "2 years",
    weight: 0.8,
    dimensions: { length: 6.3, width: 4.7, height: 3.1 },
    ratings: { average: 4.5, totalReviews: 600 },
    isActive: true,
    isFeatured: false,
    salesCount: 1800,
  },
  {
    name: "Seasonic Focus GX-750",
    category: "Power Supply",
    brand: "Seasonic",
    specifications: [
      { key: "Wattage", value: "750W" },
      { key: "Efficiency", value: "80+ Gold" },
      { key: "Modularity", value: "Fully Modular" },
    ],
    originalPrice: 129,
    discountPercentage: 8,
    finalPrice: 118.68,
    stock: 22,
    availability: "In Stock",
    images: ["https://example.com/images/seasonic-750w.jpg"],
    description: "Reliable and efficient power supply for gaming builds.",
    sku: "PSU-SEA-GX750",
    features: ["Silent Fan", "Japanese Capacitors"],
    warranty: "10 years",
    weight: 2,
    dimensions: { length: 6.3, width: 5.9, height: 3.4 },
    ratings: { average: 4.8, totalReviews: 300 },
    isActive: true,
    isFeatured: true,
    salesCount: 800,
  },
  {
    name: "NZXT H510 Mid Tower Case",
    category: "Case",
    brand: "NZXT",
    specifications: [
      { key: "Form Factor", value: "Mid Tower" },
      { key: "Material", value: "Steel/Tempered Glass" },
      { key: "Color", value: "Matte Black" },
    ],
    originalPrice: 89,
    discountPercentage: 10,
    finalPrice: 80.1,
    stock: 18,
    availability: "In Stock",
    images: ["https://example.com/images/nzxt-h510.jpg"],
    description: "Minimalist mid-tower case with excellent cable management.",
    sku: "CASE-NZXT-H510",
    features: ["Tempered Glass", "USB 3.1"],
    warranty: "2 years",
    weight: 6.5,
    dimensions: { length: 16.8, width: 8.3, height: 18.1 },
    ratings: { average: 4.6, totalReviews: 390 },
    isActive: true,
    isFeatured: false,
    salesCount: 950,
  },
  {
    name: "MSI MPG Z690 Carbon WiFi",
    category: "Motherboard",
    brand: "MSI",
    specifications: [
      { key: "Chipset", value: "Z690" },
      { key: "Socket", value: "LGA1700" },
      { key: "Wi-Fi", value: "Wi-Fi 6E" },
      { key: "Form Factor", value: "ATX" },
    ],
    originalPrice: 379,
    discountPercentage: 5,
    finalPrice: 360.05,
    stock: 10,
    availability: "In Stock",
    images: ["https://example.com/images/msi-z690-carbon.jpg"],
    description: "Premium motherboard with robust power delivery.",
    sku: "MB-MSI-Z690C",
    features: ["DDR5", "PCIe 5.0"],
    warranty: "3 years",
    weight: 1.3,
    dimensions: { length: 12, width: 9.6, height: 2 },
    ratings: { average: 4.7, totalReviews: 310 },
    isActive: true,
    isFeatured: true,
    salesCount: 620,
  },

  {
    name: "NZXT H510 Mid Tower Case",
    category: "Case",
    brand: "NZXT",
    specifications: [
      { key: "Form Factor", value: "Mid Tower" },
      { key: "Material", value: "Steel/Tempered Glass" },
      { key: "Color", value: "Matte Black" },
    ],
    originalPrice: 89,
    discountPercentage: 10,
    finalPrice: 80.1,
    stock: 25,
    availability: "In Stock",
    images: ["https://example.com/images/nzxt-h510.jpg"],
    description:
      "Sleek, modern case with excellent airflow and cable management.",
    sku: "CASE-NZXT-H510-1",
    features: ["Tempered Glass Side Panel", "Front USB-C"],
    warranty: "2 years",
    weight: 6.6,
    dimensions: { length: 16.8, width: 8.3, height: 18.1 },
    ratings: { average: 4.6, totalReviews: 500 },
    isActive: true,
    isFeatured: false,
    salesCount: 900,
  },
  {
    name: "G.Skill Trident Z5 RGB 32GB",
    category: "RAM",
    brand: "G.Skill",
    specifications: [
      { key: "Capacity", value: "32GB (2x16GB)" },
      { key: "Speed", value: "6400MHz" },
      { key: "Type", value: "DDR5" },
    ],
    originalPrice: 210,
    discountPercentage: 15,
    finalPrice: 178.5,
    stock: 30,
    availability: "In Stock",
    images: ["https://example.com/images/trident-z5.jpg"],
    description: "Ultra-fast DDR5 memory with stunning RGB lighting.",
    sku: "RAM-GSK-Z5-32GB",
    features: ["RGB Lighting", "High Performance"],
    warranty: "Lifetime",
    weight: 0.2,
    dimensions: { length: 5.3, width: 1.3, height: 0.3 },
    ratings: { average: 4.9, totalReviews: 150 },
    isActive: true,
    isFeatured: true,
    salesCount: 1300,
  },
  {
    name: "Western Digital Black 2TB NVMe SSD",
    category: "Storage",
    brand: "Western Digital",
    specifications: [
      { key: "Capacity", value: "2TB" },
      { key: "Interface", value: "PCIe Gen4" },
      { key: "Form Factor", value: "M.2" },
    ],
    originalPrice: 249,
    discountPercentage: 12,
    finalPrice: 219.12,
    stock: 27,
    availability: "In Stock",
    images: ["https://example.com/images/wd-black-2tb.jpg"],
    description: "Blazing-fast SSD for gaming and content creation.",
    sku: "SSD-WD-BLACK-2TB",
    features: ["Gaming Mode", "Thermal Throttle Protection"],
    warranty: "5 years",
    weight: 0.08,
    dimensions: { length: 3.15, width: 0.87, height: 0.09 },
    ratings: { average: 4.8, totalReviews: 310 },
    isActive: true,
    isFeatured: true,
    salesCount: 1600,
  },
  {
    name: "Be Quiet! Dark Rock Pro 4",
    category: "Cooler",
    brand: "Be Quiet!",
    specifications: [
      { key: "Type", value: "Air Cooler" },
      { key: "Noise Level", value: "24.3 dBA" },
      { key: "Fan Speed", value: "1200 RPM" },
    ],
    originalPrice: 89,
    discountPercentage: 5,
    finalPrice: 84.55,
    stock: 17,
    availability: "In Stock",
    images: ["https://example.com/images/darkrock-pro4.jpg"],
    description: "Silent high-performance CPU cooler with dual fans.",
    sku: "CLR-BQ-DRP4",
    features: ["Silent Wings", "Dual Tower Design"],
    warranty: "3 years",
    weight: 1.13,
    dimensions: { length: 6.4, width: 5.7, height: 6.3 },
    ratings: { average: 4.9, totalReviews: 220 },
    isActive: true,
    isFeatured: true,
    salesCount: 1100,
  },
  {
    name: "EVGA SuperNOVA 850 G6",
    category: "Power Supply",
    brand: "EVGA",
    specifications: [
      { key: "Wattage", value: "850W" },
      { key: "Efficiency", value: "80+ Gold" },
      { key: "Modularity", value: "Fully Modular" },
    ],
    originalPrice: 139,
    discountPercentage: 10,
    finalPrice: 125.1,
    stock: 19,
    availability: "In Stock",
    images: ["https://example.com/images/evga-850w.jpg"],
    description: "High-efficiency PSU with excellent reliability.",
    sku: "PSU-EVGA-850G6",
    features: ["Eco Mode", "Quiet Operation"],
    warranty: "10 years",
    weight: 2.1,
    dimensions: { length: 6.3, width: 5.9, height: 3.4 },
    ratings: { average: 4.7, totalReviews: 270 },
    isActive: true,
    isFeatured: true,
    salesCount: 1000,
  },
  {
    name: "MSI MAG B650 TOMAHAWK",
    category: "Motherboard",
    brand: "MSI",
    specifications: [
      { key: "Chipset", value: "B650" },
      { key: "Socket", value: "AM5" },
      { key: "Form Factor", value: "ATX" },
      { key: "RAM Support", value: "DDR5" },
    ],
    originalPrice: 219,
    discountPercentage: 8,
    finalPrice: 201.48,
    stock: 16,
    availability: "In Stock",
    images: ["https://example.com/images/msi-b650.jpg"],
    description: "Feature-rich AM5 motherboard for Ryzen 7000 CPUs.",
    sku: "MB-MSI-B650TOMA",
    features: ["PCIe 5.0", "2.5G LAN"],
    warranty: "3 years",
    weight: 1.3,
    dimensions: { length: 12, width: 9.6, height: 2 },
    ratings: { average: 4.6, totalReviews: 190 },
    isActive: true,
    isFeatured: false,
    salesCount: 850,
  },
  {
    name: "Intel Arc A770 16GB",
    category: "GPU",
    brand: "Intel",
    specifications: [
      { key: "Memory", value: "16GB GDDR6" },
      { key: "Clock Speed", value: "2100 MHz" },
      { key: "TDP", value: "225W" },
      { key: "Interface", value: "PCIe 4.0" },
    ],
    originalPrice: 349,
    discountPercentage: 10,
    finalPrice: 314.1,
    stock: 10,
    availability: "In Stock",
    images: ["https://example.com/images/arc-a770.jpg"],
    description: "Intel’s entry into the high-performance GPU market.",
    sku: "GPU-INTEL-A770",
    features: ["Ray Tracing", "XeSS Upscaling"],
    warranty: "2 years",
    weight: 1.2,
    dimensions: { length: 11, width: 5, height: 2.2 },
    ratings: { average: 4.2, totalReviews: 180 },
    isActive: true,
    isFeatured: false,
    salesCount: 500,
  },
  {
    name: "ADATA XPG Lancer 32GB RGB DDR5",
    category: "RAM",
    brand: "ADATA",
    specifications: [
      { key: "Capacity", value: "32GB (2x16GB)" },
      { key: "Speed", value: "6000MHz" },
      { key: "Type", value: "DDR5" },
    ],
    originalPrice: 179,
    discountPercentage: 13,
    finalPrice: 155.73,
    stock: 23,
    availability: "In Stock",
    images: ["https://example.com/images/xpg-lancer.jpg"],
    description: "Gaming RAM with aggressive styling and RGB effects.",
    sku: "RAM-ADATA-LANCER",
    features: ["RGB", "PMIC"],
    warranty: "Lifetime",
    weight: 0.18,
    dimensions: { length: 5.4, width: 1.3, height: 0.28 },
    ratings: { average: 4.5, totalReviews: 140 },
    isActive: true,
    isFeatured: false,
    salesCount: 980,
  },
  {
    name: "Noctua NH-D15 Chromax Black",
    category: "Cooler",
    brand: "Noctua",
    specifications: [
      { key: "Type", value: "Air Cooler" },
      { key: "Fan Speed", value: "1500 RPM" },
      { key: "Noise Level", value: "24.6 dBA" },
    ],
    originalPrice: 99,
    discountPercentage: 7,
    finalPrice: 92.07,
    stock: 12,
    availability: "In Stock",
    images: ["https://example.com/images/nhd15-black.jpg"],
    description: "Best-in-class silent air cooler with black aesthetic.",
    sku: "CLR-NOCTUA-NHD15",
    features: ["Dual Tower", "Dual Fan"],
    warranty: "6 years",
    weight: 1.32,
    dimensions: { length: 6.5, width: 5.9, height: 6.4 },
    ratings: { average: 5.0, totalReviews: 450 },
    isActive: true,
    isFeatured: true,
    salesCount: 1250,
  },
];
export default sampleProducts;
